"""Core shared utilities for DTAM."""

from dtam.core.exceptions import (
    AcquisitionError,
    ActuatorError,
    AgentExecutionError,
    ApprovalRequiredError,
    ArtifactError,
    CalibrationError,
    CommunicationError,
    ConfigurationError,
    DtamError,
    ErrorSeverity,
    InterlockError,
    ModelError,
    Recoverability,
    SafetyViolationError,
    SensorUnavailableError,
    StateEstimationError,
    SynchronizationError,
    ToolExecutionError,
)

__all__ = [
    "AcquisitionError",
    "ActuatorError",
    "AgentExecutionError",
    "ApprovalRequiredError",
    "ArtifactError",
    "CalibrationError",
    "CommunicationError",
    "ConfigurationError",
    "DtamError",
    "ErrorSeverity",
    "InterlockError",
    "ModelError",
    "Recoverability",
    "SafetyViolationError",
    "SensorUnavailableError",
    "StateEstimationError",
    "SynchronizationError",
    "ToolExecutionError",
]
